FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY models/ ./models/

ENV MODELS_DIR="./models"
ENV USE_ENSEMBLE="True"
ENV MODEL_PATH="./models/BRAIN_MRI_EFFICIENTNET.pth"
ENV CLASS_LABELS="Glioma,Meningioma,No Tumor,Pituitary"
ENV GRADCAM_OPACITY="0.4"
ENV GRADCAM_COLORMAP="jet"
ENV HOST="0.0.0.0"
ENV PORT="8000"

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
